### ISSUE TITLE
Starting from today we cannot connect to JIRA Cloud

### ISSUE THREAD

**Issue by bluish5** [carstengehling/jirastopwatch#138]
Hello,
starting from today we cannot connect to JIRA Cloud, both me and my collegue.

If I click on Not connected label this is the error:
![immagine](https://user-images.githubusercontent.com/11028113/56136057-42acde00-5f92-11e9-9a89-9523bf096540.png)

This is the log that I have for Jira StopWatch if I enable it:
```
15/04/2019 15:18:05 Request: https://mycompany.atlassian.net/rest/auth/1/session
15/04/2019 15:18:05 Response: Unauthorized - {"errorMessages":["Accesso fallito"],"errors":{}}
15/04/2019 15:18:05 Try to re-authenticate
15/04/2019 15:18:05 Request: https://mycompany.atlassian.net/rest/auth/1/session
15/04/2019 15:18:06 Response: Unauthorized - {"errorMessages":["Accesso fallito"],"errors":{}}
15/04/2019 15:18:06 Request: https://mycompany.atlassian.net/rest/auth/1/session
15/04/2019 15:18:06 Response: Unauthorized - {"errorMessages":["Non hai effettuato l'autenticazione. L'autenticazione รจ necessaria per eseguire q
15/04/2019 15:18:06 Try to re-authenticate
15/04/2019 15:18:06 Request: https://mycompany.atlassian.net/rest/auth/1/session
15/04/2019 15:18:06 Response: Unauthorized - {"errorMessages":["Accesso fallito"],"errors":{}}
```

**Comment by Killtek** [comment]
Same here

**Comment by mmccauley316** [comment]
Having the same issue here.

**Comment by dbraaten42** [comment]
As was mentioned on a different thread https://github.com/carstengehling/jirastopwatch/issues/125  Jira is deprecating the API Stopwatch uses for auth.  I assume it actually got turned off today.  :(

**Comment by tcbusatta** [comment]
Same here...

**Comment by carlclark267ds** [comment]
We have also run into this issue.  

This document (https://developer.atlassian.com/cloud/jira/platform/jira-rest-api-basic-authentication/) describes how basic auth will no longer support passwords but does indicate that it will support API Tokens.

API tokens for a user can be created here https://id.atlassian.com/manage/api-tokens.

In theory changing the password to an API token should allow connection.  **However**, Jira StopWatch appears to be passing the credentials as part of a request body as opposed to a normal Authorization HTTP header.

We have managed to update the code to include the HTTP header and have got it **up and running**, we will test it for a while to ensure it's working.

**Comment by carlclark267ds** [comment]
I have committed our codes changes into a fork of the code if anyone needs to grab a copy - https://github.com/carlclark267ds/jirastopwatch.

**Comment by bluish5** [comment]
Thank you Carl!
I downloaded your fork, compiled it and run.
I created an API token and set in Jira StopWatch, but I still cannot connect and in the log I find:
```
16/04/2019 10:52:29 Request: https://mycompany.atlassian.net/rest/auth/1/session
16/04/2019 10:52:30 Response: Unauthorized - 








<html>

<head>
    <title>Unauthorized (401)</title>
    





<!--[if IE]><![endif]-->
<sc
16/04/2019 10:52:30 Try to re-authenticate
16/04/2019 10:52:30 Request: https://mycompany.atlassian.net/rest/auth/1/session
16/04/2019 10:52:30 Response: Unauthorized - 








<html>

<head>
    <title>Unauthorized (401)</title>
    





<!--[if IE]><![endif]-->
<script type="text/javascript" >
    var contextPath = '';
    var DeferScripts = { deferState: 'disabled' };
</script>
<script>
window.WRM=window.WRM||{};window.WRM._unparsedData=window.WRM._unparsedData||{};window.WRM._unparsedErrors=window.WRM._unparsedErrors||{};
WRM._unparsedData["com.atlassian.plugins.atlassian-plugins-webresource-plugin:context-path.context-path"]="\"\"";
WRM._unparsedData["com.atlassian.plugins.atlassian-plugins-webresource-rest:curl.cross-origin-resources"]="false";
WRM._unparsedData["jira.webresources:feature-flags.feature-flag-data"]="{\"enabled-feature-keys\":[\"jira.plugin.devstatus.smartcommits.dvcs.enabled\",\"nps.survey.inline.dialog\",\"jira.export.excel.enabled\",\"com.atlassian.jira.plugins.mail.internal.enabled\",\"sd.new.settings.sidebar.location\",\"re-enable.group.endpoints.jra-60287\",\"dvcs.connector.smartcommits.disabled\",\"unified.usermanagement\",\"com.atlassian.jira.projects.issuenavigator\",\"jira.issue.search.jql.indexprimary.enabled\",\"jira.issue.search.api.indexprimary.enabled\",\"com.atlassian.jira.projects.issue.summary.vignettes\",\"atlassian.aui.raphael.disabled\",\"fusion.dvcs.use_amq_for_executors.enabled\",\"connect.dependencies.allow\",\"com.atlassian.jira.config.CoreFeatures.PERMISSIONS_MANAGED_BY_UM\",\"com.atlassian.jira.projects.ProjectCentricNavigation.Switch\",\"com.atlassian.jira.config.CoreFeatures.ON_DEMAND\",\"atlassian.plugin.aci.enabled\",\"com.atlassian.jira.agile.darkfeature.kanplan\",\"connect.no-applinks\",\"fusion.dvcs.use_amq_to_invoke_sync.enabled\",\"com.atlassian.portfolio.classicPlans.sunset\",\"com.atlassian.rm.portfolio.vertigo.issueloading.Database\",\"jira.baseurl.cdn.enabled\",\"fusion.bitbucket.rebrand\",\"com.atlassian.portfolio.integrations.ClassicPlans.disabled\",\"connect.authentication.oauth2.impersonation\",\"sd.email.mailbox.poppy.migration.poppyonly.enabled\",\"dvcs.connector.repositorydao.ao.enabled\",\"fusion.devstatus.de
16/04/2019 10:52:30 Request: https://mycompany.atlassian.net/rest/auth/1/session
16/04/2019 10:52:31 Response: Unauthorized - 








<html>

<head>
    <title>Unauthorized (401)</title>
    





<!--[if IE]><![endif]-->
<sc
16/04/2019 10:52:31 Try to re-authenticate
16/04/2019 10:52:31 Request: https://mycompany.atlassian.net/rest/auth/1/session
16/04/2019 10:52:31 Response: Unauthorized - 








<html>

<head>
    <title>Unauthorized (401)</title>
    





<!--[if IE]><![endif]-->
<script type="text/javascript" >
    var contextPath = '';
    var DeferScripts = { deferState: 'disabled' };
</script>
<script>
window.WRM=window.WRM||{};window.WRM._unparsedData=window.WRM._unparsedData||{};window.WRM._unparsedErrors=window.WRM._unparsedErrors||{};
WRM._unparsedData["com.atlassian.plugins.atlassian-plugins-webresource-plugin:context-path.context-path"]="\"\"";
WRM._unparsedData["com.atlassian.plugins.atlassian-plugins-webresource-rest:curl.cross-origin-resources"]="false";
WRM._unparsedData["jira.webresources:feature-flags.feature-flag-data"]="{\"enabled-feature-keys\":[\"jira.plugin.devstatus.smartcommits.dvcs.enabled\",\"nps.survey.inline.dialog\",\"jira.export.excel.enabled\",\"com.atlassian.jira.plugins.mail.internal.enabled\",\"sd.new.settings.sidebar.location\",\"re-enable.group.endpoints.jra-60287\",\"dvcs.connector.smartcommits.disabled\",\"unified.usermanagement\",\"com.atlassian.jira.projects.issuenavigator\",\"jira.issue.search.jql.indexprimary.enabled\",\"jira.issue.search.api.indexprimary.enabled\",\"com.atlassian.jira.projects.issue.summary.vignettes\",\"atlassian.aui.raphael.disabled\",\"fusion.dvcs.use_amq_for_executors.enabled\",\"connect.dependencies.allow\",\"com.atlassian.jira.config.CoreFeatures.PERMISSIONS_MANAGED_BY_UM\",\"com.atlassian.jira.projects.ProjectCentricNavigation.Switch\",\"com.atlassian.jira.config.CoreFeatures.ON_DEMAND\",\"atlassian.plugin.aci.enabled\",\"com.atlassian.jira.agile.darkfeature.kanplan\",\"connect.no-applinks\",\"fusion.dvcs.use_amq_to_invoke_sync.enabled\",\"com.atlassian.portfolio.classicPlans.sunset\",\"com.atlassian.rm.portfolio.vertigo.issueloading.Database\",\"jira.baseurl.cdn.enabled\",\"fusion.bitbucket.rebrand\",\"com.atlassian.portfolio.integrations.ClassicPlans.disabled\",\"connect.authentication.oauth2.impersonation\",\"sd.email.mailbox.poppy.migration.poppyonly.enabled\",\"dvcs.connector.repositorydao.ao.enabled\",\"fusion.devstatus.de

```

**Comment by eliaspww** [comment]
Same issue.

**Comment by bluish5** [comment]
I found the problem: I was using my username instead of my email (I suggest to change the second label from "Username" to "Email", in settings form).

Summarizing you should download Carl's fork of the Jira StopWatch (https://github.com/carlclark267ds/jirastopwatch), compile it in Visual Studio and install it. Then in its settings form set your email and the token, that you generate following the link in the form itself.
If you have problems compiling in Visual Studio, here you have the compiled program! 
[Jira StopWatch 2.3.0.zip](https://github.com/carstengehling/jirastopwatch/files/3084923/Jira.StopWatch.2.3.0.zip)

**Comment by tcbusatta** [comment]
Thanks Carl and bluish5, it's working!
There is just a little issue: the filter is not working properly for me. Instead of showing only my issues in "My open issues", it shows all sprint issues.

**Comment by bluish5** [comment]
I have the same issue with filters.

But at least now we can commit work logs ;)

**Comment by 8khan** [comment]
i think its a windows issue, because i usually dont reboot my laptop until today i can use jirastopwatch, but today i reboot my laptop to install some windows updates after that jirastopwatch dont connect :(

i hope it help to solve that issue

**Comment by carlclark267ds** [comment]
@bluish5 - You're correct with the email address instead of the username.  I will make the change to the label on the form.  Thanks.

@8khan it's not a Windows issue, definitely a code issue.

@bluish5 and @tcbusatta change to the filter is unexpected, I will have a look as soon as I can.

**Comment by carlclark267ds** [comment]
I will look at dropping the executable version today for those who don't want to build it in Visual Studio.

**Comment by 8khan** [comment]
@carlclark267ds mmm ok, but its so mysterious because jirestopwatch didnt fail until windows update :/ coincidence maybe?

**Comment by miber74** [comment]
@carlclark267ds thanks for the fix and @bluish5 thanks for the executable. Great to have StopWatch running again. 
@8khan I assume that your are kept authenticated as long as you are still logged in to Windows but you loose that when rebooting. I have colleagues that are still fine with previous version of StopWatch and they haven't rebooted.

**Comment by carstengehling** [comment]
@carlclark267ds If you could send me a pull request, I will be happy to merge it in and send out an "official" release.

My time for the project has diminished a lot, but it would be sad to see the entire thing fade out just because of authentication.

**Comment by jamienrogers** [comment]
@carstengehling So looking forward to the "official release". Can't work without my adored Jira StopWatch.

**Comment by 8khan** [comment]
@miber74 maybe you have a good point.

@carstengehling thanks by the initiative of a official release

**Comment by cghaws** [comment]
@carstengehling , @carlclark267ds , is there any update on this? we'd love to see that official release soon.

**Comment by bellamatte** [comment]
Hi @carstengehling, I've made a pull request to solve this issue (see #139).

**Comment by cristiancarraro** [comment]
thank you very much @ carlclark267ds . Genius!

**Comment by Tarekajaj** [comment]
Thanks @bluish5 & @carlclark267ds,
Any update regarding issue with filters ?

**Comment by jamienrogers** [comment]
Any updates on the new version? @carstengehling

**Comment by carlclark267ds** [comment]
@carstengehling , @bluish5 , @jamienrogers , @cristiancarraro - hi all.  Apologies I was on leave last week I will look into submitting pull request today/tomorrow.

**Comment by jamienrogers** [comment]
@carlclark267ds thank you! Any updates?

**Comment by carstengehling** [comment]
Sorry to be so late with this, but I finally found the time to add the pull reuest from @bellamatte - thank you a lot for this!

Please get the latest release at https://github.com/carstengehling/jirastopwatch/releases/latest and you should be good to go again.

**Comment by Tarekajaj** [comment]
@carstengehling Thank you very much
